### ISSUE TITLE
Error when loading app first time, DataGridView Default Error Dialog

### ISSUE THREAD

**Issue by profucius** [Fr33dan/GPSaveConverter#10]
Hello. I just downloaded your software and ran it, and got this error.

![image](https://user-images.githubusercontent.com/18254607/180252507-409e024d-b9a8-40a7-861c-a0432c552c5c.png)

After I click OK, it just shows this and nothing else happens.

![image](https://user-images.githubusercontent.com/18254607/180252635-19bb092f-138e-4759-8f96-644624f744ec.png)

I'm on Windows 11 if that helps. Thanks

**Comment by profucius** [comment]
Update: I spun up a Windows 10 VM and ran the app, and it worked just fine. I wonder if it's not compatible with Windows 11? Or something like a .NET etc?

**Comment by Fr33dan** [comment]
I'm actually closing this issue because it is a duplicate of issue #8. Please check that thread for further updates.
