### ISSUE TITLE
Two Point Hospital - Error

### ISSUE THREAD

**Issue by PCM4st3r** [Fr33dan/GPSaveConverter#13]
Hello, first of all, thank you for this very useful tool that I will probably need for many other games.

Unfortunately I am forced to contact you because I cannot convert my Two Point Hospital saves from Microsoft Store to another client, the following error message appears:

![err](https://user-images.githubusercontent.com/112161275/186853931-0f22cfbe-0f65-49f7-8a68-f4dc38e9ab27.png)

Unfortunately it happens with almost all save files (except a couple, like the career one)

I haven't been able to figure out the cause of the problem.

thank you
greetings.

**Comment by Fr33dan** [comment]
This is a bug introduced by another bugfix a few updates back that causes this error of the non-Xbox file does not already exist. Pushing a fix update now.

**Comment by PCM4st3r** [comment]
Now it works, thanks a lot. :D
