### ISSUE TITLE
Forza 5 error

### ISSUE THREAD

**Issue by nickys2466** [Fr33dan/GPSaveConverter#16]
![image](https://user-images.githubusercontent.com/113197433/189390353-171d3922-e061-4681-9f80-9feda4b209c3.png)

How do I fix this?

**Comment by Fr33dan** [comment]
I need more details. It looks like you were trying to move a save file from the non-Xbox version to the Xbox version. Which file were you trying to move?

Note that only the profile data can be migrated at this time.

**Comment by nickys2466** [comment]
![image](https://user-images.githubusercontent.com/113197433/189472438-75b4d061-b223-43ac-821e-40853f160aeb.png)
I'm trying to move my saved file from Xbox to Steam but it seems that it can't access the file from Xbox

**Comment by Fr33dan** [comment]
There are three issues at play here one of which is my fault. 

First is that you have not opened the Xbox version. You must open the game to create the containers GPSC needs to put your non-Xbox save files in. GPSC cannot create Xbox save file storage containers and the game must create them itself before GPSC can modify them. 

Second, the you have only selected one of the garage thumbnail files. Those files are not supported. Only the files that start with "User_" are support at this time. It is my understanding that other files can be copied, but the game will think they are corrupt. But this shouldn't be a huge detrement as once you have the profile loaded the game itself seems to restore this data on it's own somehow.

The third issue is that even if you had done the first two things correctly there is a bug introduced by some changes I made to avoid ambiguous matches. Please download the updated version that will be posted shortly.

**Comment by Fr33dan** [comment]
This comment is more for my documentation later than it will be helpful to you, but the file translation matching had an error caused by the Regex being needing to be escaped after the substitutions were made, but before the Regex was made exact to prevent ambiguous matches.

**Comment by nickys2466** [comment]
I already have the Xbox version installed and play it for a long time before I bought the steam version. I download your latest version and it still shows that my Xbox saved is empty.

**Comment by Fr33dan** [comment]
I've never seen that before. I've installed it on my system and verified it shows save files for me. If you use the "Explore Xbox Files" button where does it take you and is there anything there? Also could you please turn your log level up to "TRACE" in the preferences and relaunch the software. Then attach the log file to this thread.

**Comment by nickys2466** [comment]
It works now, thank you very much
