### ISSUE TITLE
Issue with Forza Horizon 5 

### ISSUE THREAD

**Issue by Marat777475** [Fr33dan/GPSaveConverter#25]
#21 I want to transfer my save to MS Store but i can't due to this error.

![Desktop Screenshot 2022 12 15 - 17 14 15 68](https://user-images.githubusercontent.com/120501684/207822614-0bba812c-20b6-4d50-a036-91446282850c.png)

**Comment by Steve777475** [comment]
It writes 'Ambiguous Xbox container results'

**Comment by Steve777475** [comment]
If anyone can help me. I'll appreciate it.

**Comment by Steve777475** [comment]
Let me know what causes this issue, And i hope there's solution to it.

**Comment by Fr33dan** [comment]
Hi, I operate on the EST time so replies may take some time when it is the middle of the night for me. 

Your screenshot has me a touch confused. Your Xbox files shows the transaction log selected but the non-xbox files show the profile data. They should be synced so when you select a file in one box the matching one in the other should be highlighted. Have you modified the file translation?

**Comment by Fr33dan** [comment]
Also your Xbox files do not contain a profile data file at all. Are you sure you got into the game enough for all the save files to be initialized?

**Comment by Steve777475** [comment]
@Fr33dan so, Should i play the game for a few hours and then transfer yeah?

**Comment by Steve777475** [comment]
![20221215_223704.jpg](https://user-images.githubusercontent.com/120501684/207888597-db5a3865-9953-4245-8b19-745863fe9a50.jpg)  So, I have profile on non-Xbox files and my Steam Account. And what do I have to do to transfer??

**Comment by Fr33dan** [comment]
Wait a bit, I was testing the P5R profile someone else suggested and discovered some cases that have issues with matching. There will be an update soon that should fix the problems.

**Comment by Steve777475** [comment]
Ok I'll wait. If I have my save transfered to Xbox. And then go to FH5. Will get invalid profile (I mean the profile you're trying to login is not available) if yes. Is there a solution to that?

**Comment by Steve777475** [comment]
Yes I would like to answer. Is there chance to get banned after that right now. Or medium (mean 50-50%)?

**Comment by Fr33dan** [comment]
If you get it transfered correct it should work according to other reports. If the profile has been transfered correctly but you get a profile corrupted report then they have changed something and broken compatiblity and there is nothing we can do.

This converter relies on both the Xbox and non-Xbox version of the game using the same save file format, but with different names. Some games actually use slightly different file formats between versions and the tool will not work. So far I've never heard of a game that worked before to stop working because of an update so I'm fairly confident FH5 can work for the profile data. That said they are changing something, I haven't updated FH5 in some time but don't have the meta file you show, but a profiledata file instead:
![image](https://user-images.githubusercontent.com/4670572/207899944-82256b63-f31d-4922-88f2-2958a052f6d9.png)


All I can go on is what other people have said and so far no one has reported that they have been banned.

Update is out now, seems to be working either direction.

**Comment by Steve777475** [comment]
If no one got banned for this. Then I should hope that I will not get banned too. Ok I'll try a new update and transfer it correctly that should work hopefully.

**Comment by Steve777475** [comment]
![20221215_234818.jpg](https://user-images.githubusercontent.com/120501684/207905794-567c99df-368a-4cf3-8b57-9b4dfca1150d.jpg) Like this

**Comment by Steve777475** [comment]
Should I click Yes or No?

**Comment by Fr33dan** [comment]
Yes

**Comment by Fr33dan** [comment]
It may crash when you do so and have to be re-opened. This is the first time that feature has been used, that is what it did for me. It may need further testing.

**Comment by Steve777475** [comment]
Ok, but I don't see Fh5.

**Comment by Steve777475** [comment]
In potential Xbox Packages.

**Comment by Fr33dan** [comment]
Did you restart the converter?

**Comment by Steve777475** [comment]
Yes. I see it

**Comment by Steve777475** [comment]
And now, what do I have to do to transfer?

**Comment by Fr33dan** [comment]
Yes, select profiledat and use the single up arrow to move only the selected file from non-Xbox to Xbox.

**Comment by Steve777475** [comment]
I hope that will work and. I will not get banned

**Comment by Steve777475** [comment]
And then launch the game on another platform? MS store?

**Comment by Steve777475** [comment]
![20221216_010746.jpg](https://user-images.githubusercontent.com/120501684/207923524-a1e671ea-462e-435d-8679-45db636daa9a.jpg) I still have this error 'Ambiguous Xbox container results' Is there a solution to solve it?

**Comment by Steve777475** [comment]
May be I chose incorrect folder or I have to rename it that mentioned in error

**Comment by Steve777475** [comment]
![20221216_011206.jpg](https://user-images.githubusercontent.com/120501684/207924660-7ecd657c-2812-44cd-8499-a9b17c30cba6.jpg) Do I have to rename this folder?

**Comment by Steve777475** [comment]
Or profiledata's name?

**Comment by Fr33dan** [comment]
So I've just noticed your container names in that the second two don't fit. I've not seen a case where they are not the same so I don't understand why that would be if the first two did fit. Please use File > Copy Save Tile Table(s) and then paste the results here.

**Comment by Steve777475** [comment]
Ok

**Comment by Fr33dan** [comment]
Your userprofile in the non-Xbox safe files is 901FBB83F62A4, but your xbox profile id is 901F6B14145A3 (without the leading zeros). At a glance they look very similar so I didn't notice until now.

It is my understanding that when you use the steam version that you must still sign into the an xbox profile. This converter assumes you are using the same profile in both versions. If not then you should try naming the non-Xbox file to match the xbox profile id (User_901F6B14145A3.ProfileData). Then make sure there is only one container that has that ID.

Do not attempt to modify the Xbox save files/folders directly. The button to view those files is just for users to make a backup (which is actually largely unnessesary as xbox cloud save already has everything backed up and will restore it if the files become corrupted).

Also just in case something is wrong with the game libary use File > Preferences > Reset All just to make sure everything is running in a clean state.

**Comment by Steve777475** [comment]
Ibe of the folders should have one container that has the same ID. I'll try

**Comment by Steve777475** [comment]
How can  I differ out that one of containers has the same ID. Should I open it?

**Comment by Steve777475** [comment]
Should I rename profile data and them move it up?

**Comment by Steve777475** [comment]
![20221216_143028.jpg](https://user-images.githubusercontent.com/120501684/208036750-09170383-51a8-40ab-92d6-baefebd85650.jpg)   Here.

**Comment by Steve777475** [comment]
And then I should open one of two containers in my two folders that should contain the same ID?

**Comment by Steve777475** [comment]
Let me know

**Comment by Steve777475** [comment]
@Fr33dan, Should i rename Profiledata and then find one container to make sure that it has the same ID and then move it up to Xbox Save Files?

**Comment by Fr33dan** [comment]
I beleive that from your most recent screenshot you have already renamed the files as needed and that you should be able to press the single up arrow to move the file to the Xbox save files and achieve the goal you want.

**Comment by Steve777475** [comment]
Ok. i hope it will work, if yes, I'll say thanks for helping me.

**Comment by Steve777475** [comment]
I entered the game and I see this issue.![20221217_011418.jpg](https://user-images.githubusercontent.com/120501684/208152486-e5e878bc-9f41-4c8c-ab6c-77b6b8325ea5.jpg)

**Comment by Steve777475** [comment]
It says me 'Invalid profile'. 'The Forza Horizon profile you are trying to load is no longer available.' Did i transfer it incorrectly?

**Comment by Steve777475** [comment]
If yes, Let me know what to do.

**Comment by Steve777475** [comment]
I hope there is a solution to this.

**Comment by Steve777475** [comment]
@Fr33dan, I entered FH5 and i tried to press continue to enter my progress and then i see this error. Is there a solution to this?

**Comment by Steve777475** [comment]
It says me 'Invalid profile'. 'The Forza Horizon profile you are trying to load is no longer available.' Did i transfer it incorrectly?

**Comment by Steve777475** [comment]
If yes, let me know what to do ans how to fix it

**Comment by Steve777475** [comment]
@Fr33dan, I renamed profiledata and then transfered to Xbox Save Files and i entered  the game and i see this problem.

**Comment by Steve777475** [comment]
@Fr33dan , Did I transfer my save incorrectly. If yes, how to solve it?

**Comment by Fr33dan** [comment]
I can't tell if you've done it right without setting the what the converter shows for your Xbox save files. Based on what you has before I'm inclined to think you got it but can't be sure.

This brings us to wild guessing mode. Is there a chance your non-Xbox version is out of date? Maybe you need the version flags as well?

**Comment by Steve777475** [comment]
Do I have to move not only Profile data but Versionflags file and other files from Steam folder and then move them up?

**Comment by Steve777475** [comment]
@Fr33dan I should try it.

**Comment by Steve777475** [comment]
@Fr33dan I don't think that Non-Xbox files are out of date I should check it.

**Comment by Steve777475** [comment]
@Fr33dan I mean transfer other files from Fh5's steam save folder to FH5'S Xbox save folder.

**Comment by Steve777475** [comment]
![Screenshot_20221218-175316_Google.jpg](https://user-images.githubusercontent.com/120501684/208291859-83a44a3a-36c5-4485-b205-5ac6929f254b.jpg) Trainer files from Steam to Xbox yes?

**Comment by Steve777475** [comment]
![20221218_175455.jpg](https://user-images.githubusercontent.com/120501684/208291883-1c5af633-f87f-4b2c-b636-e2bc7a4af11c.jpg)

**Comment by Steve777475** [comment]
Transfer these files from non-xbox save files and all the way to xbox save files yes?

**Comment by Steve777475** [comment]
Or some of them including VersionFlags?

**Comment by Steve777475** [comment]
And then make it FINALLY work

**Comment by Steve777475** [comment]
After moving files from Fh5's Steam save folder and all tye way to Xbox save folder FH5 and then Make it work?

**Comment by sullivan1337** [comment]
I just tried the same, and it seems to get further, however there is some error with the path translation?
![image](https://user-images.githubusercontent.com/33563292/208578322-b2488f1b-f401-4f30-87a2-c6cb67ab84f9.png)

**Comment by Steve777475** [comment]
@Fr33dan Should I do this offline?

**Comment by Steve777475** [comment]
@Fr33dan may be I should update profiledata and then move it up?

**Comment by Fr33dan** [comment]
@Steve777475 I have yet to see what your Xbox save files look like after the transfer. I complete and loading save file in the Xbox version looks like this:
![image](https://user-images.githubusercontent.com/4670572/208733370-67c79a82-8ee6-42f1-808d-53b54e7a4ed0.png)

The last modified date matching the modified date of the non-Xbox save files. Notice how all three files have the same modified date in my version, the last date that I played the game (In April since I'm in the USA and we do MM/DD/YY). In your case it looks like this date is early October although some screenshots show the 3rd and some show the 9th. If your files don't look like that or don't have the correct date then you have not copied them correctly.

**Comment by Fr33dan** [comment]
@sullivan1337 You have your files in a different location than the default steam directory and have had to select it manually I take it? You have selected the wrong folder, you want to select the folder that contains the User_[Long Code].ProfileData files directly and you seem to have picked a folder a few directories up. In your case the folder that starts with 2535446 (I'm not typing the whole number out, lol)

**Comment by sullivan1337** [comment]
This is actually a Microsoft version, not Steam. 
Does that mean this will not work? All the profile and container names seemed to match up

**Comment by Fr33dan** [comment]
I don't think it matters what version you are coming from. All the files should be the same, just follow different names. I try to say Xbox vs non-Xbox to differeniate between the ones that use the Xbox ecosystem for saving, but sometimes I devolve into saying "Steam" instead of non-Xbox because that terminology can be confusing to people.

**Comment by sullivan1337** [comment]
That was indeed that issue! 

However, it looks like the Xbox Save file required a "container save" (not sure if right terminology)
So when attempting to move the save I want to use to the Xbox save location, I get this error:
![image](https://user-images.githubusercontent.com/33563292/208781437-8af2a5b4-4f15-4623-93a1-8b255e138e9f.png)

**Comment by Steve777475** [comment]
@Fr33dan So, Do I have to copy three files that have the same date and then Move them?

**Comment by Steve777475** [comment]
@Fr33dan, Or All files from Non-xbox save files and move them

**Comment by Steve777475** [comment]
Or Should I update Sices from Non-xbox save files and them move them up?

**Comment by Steve777475** [comment]
@Fr33dan sorry for asking that for the second time but Should I I transfer files from non-Xbox Save Files to Xbox Save Files offline? (I mean should I do that offline?)

**Comment by Steve777475** [comment]
@Fr33dan to not be able to get banned.

**Comment by Steve777475** [comment]
My progress on both platforms Steam and Microsoft Store should be the same.

**Comment by Steve777475** [comment]
After transferring, Files on both platforms should be the same I think.

**Comment by Steve777475** [comment]
Should I rename files' id transfer these files to Xbox save? files![20221225_122001.jpg](https://user-images.githubusercontent.com/120501684/209456874-1444d8d7-18cf-490f-9fcb-24e5b9f09cf6.jpg) Here.

**Comment by Steve777475** [comment]
@sullivan1337, I have that issue too.

**Comment by Steve777475** [comment]
I see that one file has a different date, i noticed it.

**Comment by Steve777475** [comment]
TransactionLogFile has the different date, Is there nothing i can update the date of this file?

**Comment by Steve777475** [comment]
@Fr33dan Sorry for asking too many questions but Should i update date of the files in Non-Xbox save folder?

**Comment by Steve777475** [comment]
@Fr33dan, Here ![20221225_193013.jpg](https://user-images.githubusercontent.com/120501684/209466297-5ff0c019-e719-4633-a39e-f5ccf969579c.jpg)

**Comment by Steve777475** [comment]
I just moved these files from my second PC to my phone and then i moved then from my phone into my PC thus i updated date of the files.

**Comment by Steve777475** [comment]
![Desktop Screenshot 2022 12 25 - 22 57 20 58](https://user-images.githubusercontent.com/120501684/209472881-8d732be7-ca42-43cc-84f9-bb5cf82e6611.png)

**Comment by Steve777475** [comment]
And then move them up to Xbox save files.

**Comment by Steve777475** [comment]
![Desktop Screenshot 2022 12 26 - 01 00 00 14](https://user-images.githubusercontent.com/120501684/209476407-6e84525a-aaee-4b43-86cf-03dfa02c8b1f.png) @Fr33dan Also, I want to move files to Xbox Save Files but i get this error, Is something wrong with container?

**Comment by Steve777475** [comment]
I also have changed Date of the 5 files.

**Comment by Steve777475** [comment]
I still get Invalid Profile

**Comment by Steve777475** [comment]
@sullivan1337 I have the same issue.

**Comment by sullivan1337** [comment]
Ok, plz don't comment ever 8 hours for 6 days. He'll respond when he has time/sees this

**Comment by Steve777475** [comment]
Ok, I'm sorry for Sending too many comments. I just want to get an answer. I will not do that.

**Comment by Fr33dan** [comment]
@sullivan1337 I'm confused as based on what I can see in your screenshot everything looks right. It's complaining about the container not existing, but the container is there.

I think I'm about to scrap this file translation and start over to see if I can eliminate the need to rename the files. I thought at one point I was working on a solution for that in the code but it's been months. I have some time today and it needs to be simplified.

**Comment by Fr33dan** [comment]
Okay I've figured out at least some of the problem. The improvements I made to simplify the process only work if you are coming from Steam. Basically if you are going from a Steam install on a computer to an Xbox install on the same computer it's I made it very easy, but in the process made it more difficult for anyone who is not doing exactly that.

I need to rework this code to work for any non-Xbox installations that are also non-Steam. In order to do that I need to know more about the save file structure of these installations. 

If you have the game installed from somewhere that is not Steam or the Xbox/Windows storefront, where is it keeping it's save files?

**Comment by sullivan1337** [comment]
I don't, mines directly from Xbox/Windows store

**Comment by Fr33dan** [comment]
It's been my understanding based on what @Steve777475 has said that the Windows Store version uses the same save files as the Xbox version. So what are you trying to copy?

**Comment by sullivan1337** [comment]
For my issue, I was trying to copy a Steam save I had (from a different user) to Xbox save

**Comment by Steve777475** [comment]
I transfered my save to Xbox correctly. And then I re-downloaded liveries and got thumbnails back. And then I go to favorites in my cats and I see that thumbnails load instantly for 1 sec. Is that OK?

**Comment by Steve777475** [comment]
I play the game on keyboard.

**Comment by Steve777475** [comment]
@sullivan1337, Have you managed to transfer your save?

**Comment by Steve777475** [comment]
I was trying re-downloading them again and deleting some liveries from my designs and I still have Thumbnails loading for 1 sec. Is that a problem or is it totally OK?
