### ISSUE TITLE
Forza Horizon 5 Invalid Profile after transfering save data to Xbox Save Files with Xbox Save Converter.

### ISSUE THREAD

**Issue by Steve777475** [Fr33dan/GPSaveConverter#30]
![image](https://user-images.githubusercontent.com/120501684/209517579-8f80b747-d7f1-47a0-a35b-2e468c72a45c.png)

**Comment by Steve777475** [comment]
Well, It's the same screenshot form my previous post but i have the same error with error code. I updated date of the files and then moved them into Xbox Saves Files from Steam (Non-Xbox Save Files) and i still have this error after transfering, May be i've done something wrong with transfering?

**Comment by Steve777475** [comment]
Well, It's the same screenshot from my previous post but i have the same error with error code. I updated date of the files and then moved them into Xbox Saves Files from Steam (Non-Xbox Save Files) and i still have this error after transfering, May be i've done something wrong with transfering?

**Comment by Steve777475** [comment]
Did Playground Games add a patch so that i can't be able do to it?

**Comment by Steve777475** [comment]
![Desktop Screenshot 2022 12 26 - 15 39 29 08](https://user-images.githubusercontent.com/120501684/209519646-acaca058-6118-46a8-8af6-c75dbe243bd4.png)
Here, I did transfer 3 files and then moved up.

**Comment by Steve777475** [comment]
I guess i should move five files to Xbox Save Files to achive my goal.

**Comment by Fr33dan** [comment]
I'm afraid I'm just not sure what is going on. Just to make sure I understand the problem fully I'm going to recap. If anything I say here is incorrect please correct my misunderstanding.

- You are using the MS Store version of FH5, but it created the "Xbox" save files. (This is expected since Xbox storefront seems to use the MS Store as it's backend)
- You are trying to move your save files from the non-Xbox/Steam version to the MS Store version.
- You've renamed your non-Xbox/Steam files starting with "User_" that end in "A4" to match the number ending in "A3".
- You've moved those files from the non-Xbox files to the Xbox files within the converter with the converter giving any error
- The MS Store version produces the error shown on the screen.

Here are a few things that I think are relevent, but I can't explain:

- You have an file with a BlobID/Extension with a long number ending in "meta" for your user. I've seen quite a few FH5 save files, but not seen this before.
- Your non-Xbox/Steam save files have save files that include "_Backup" after the User id. I don't understand why this would be since the game already creates a .ProfileBackup file.

**Comment by Steve777475** [comment]
I think I should move all files from Non-Xbox Save files to Xbox Save files. May be It'll solve this issue.

**Comment by Steve777475** [comment]
I'm not sure but I'm trying.

**Comment by Steve777475** [comment]
I renamed all three files from A4 to A3, and then move them up to Xbox Save Files with the single arrow, then I launch the game and with attempt to enter the game I can't enter because of that Error. I should try to move other files from Non-Xbox Save Files up. May be It requires other files including 3 of them including Profiledata.

**Comment by Fr33dan** [comment]
That is a good thing to try. Also since you may want to try re-naming the file ending in meta so that it matches the name of the one in your Xbox files.

**Comment by Steve777475** [comment]
Also I have an error with Xbox Save Converter with renamed Files.

**Comment by Steve777475** [comment]
![Desktop Screenshot 2022 12 27 - 02 35 53 76](https://user-images.githubusercontent.com/120501684/209575677-cff1b046-2755-44aa-b081-d0d17bdfd8c9.png) Here

**Comment by Fr33dan** [comment]
When you re-name the files leave the zeros at the front off so it would just start "User_901". Also you have selected some files that have not been renamed.

Remember that when you select a file on either table, the matching file will be selected on the other table. If nothing is selected, then the match isn't working and you haven't renamed the files correctly.

**Comment by Fr33dan** [comment]
You want what is shown in "Container Name 1" and "Container Name 2" to match the file names before the dot.

**Comment by Steve777475** [comment]
I don't fully get about it. But I should try to understand fully how to do it.

**Comment by Steve777475** [comment]
Ok. I'm gonna rename two of them.

**Comment by Steve777475** [comment]
![Desktop Screenshot 2022 12 27 - 03 11 17 81](https://user-images.githubusercontent.com/120501684/209577554-3419db80-3142-43a8-9d71-ad3f659b25db.png)
Here, I moved the files up to Xbox Save Files CORRECTLY I GUESS, Should that work?

**Comment by Steve777475** [comment]
If yes, I'm gonna launch the game, If no, I should try to move 2 backup files.

**Comment by Fr33dan** [comment]
As best I can tell what you have looks correct. 

I am also still curious about the last two files listed on your Xbox save files. Could you use File > Copy file table(s) to copy the full names to your clipboard and the use Ctrl + V to paste it into a comment here?

**Comment by Steve777475** [comment]
I mean 2 backup files: such as User_901FBB83F62A4_Backup.2535455429976740Meta and User_901FBB83F62A4_Backup.ProfileBackup

**Comment by Steve777475** [comment]
![Forza Horizon 5 Screenshot 2022 12 27 - 04 57 56 05](https://user-images.githubusercontent.com/120501684/209583027-4bb7ca71-f31f-4710-8c6c-9f2281f66a0c.png)
No, I got this error again. What to do?

**Comment by Steve777475** [comment]
I've done almost right and then i enetered the game and i got this issue again. Any solution to it?

**Comment by Steve777475** [comment]
Should i repair the game and try again?

**Comment by Steve777475** [comment]
@Fr33dab Do I have to Move 2 backup files I showed you in the comments?

**Comment by Steve777475** [comment]
@Fr33dan Let me know.

**Comment by Steve777475** [comment]
Or. Move 2 backup files to The second folder of my Xbox Save Files?

**Comment by Steve777475** [comment]
Here, ![209577554-3419db80-3142-43a8-9d71-ad3f659b25db.png](https://user-images.githubusercontent.com/120501684/209629976-cad9f909-05e1-40e3-826e-2fbc607b6f3a.png)

**Comment by Steve777475** [comment]
I see that 2 files from the second folder of Xbox Save files have the different date and one of them has different name.

**Comment by Steve777475** [comment]
I should rename Meta files then, May be that will fix.

**Comment by Steve777475** [comment]
But i don't know how to rename it into Steam's file's name.

**Comment by Steve777475** [comment]
- [ ] fgdgdgfgd

- [ ] dfgedfgdgdfgdgdgdddfgdgdgedgd

**Comment by Steve777475** [comment]
I guess, i renamed all files and then moved them to Xbox Save Files and i still have this error.

**Comment by Steve777475** [comment]
Should I make some progress in the game and then Transfer files to Xbox Save Files?

**Comment by Steve777475** [comment]
Should I make some progress in the game and then Transfer files from Steam to Xbox Save Files?

**Comment by Steve777475** [comment]
![Desktop Screenshot 2022 12 28 - 05 25 55 17](https://user-images.githubusercontent.com/120501684/209723944-cbfd40e6-96f8-4e25-aae5-9c447a7700a8.png)
Well, i was trying to sing out my main account and then dign in into my second account. Then i sign to my main account again. That didn't work, the game forced the restart the game and i still have that issue. But i launched the Converter and i see the second Xbox Profile with my Non Xbox profile's name.

**Comment by Steve777475** [comment]
![Desktop Screenshot 2022 12 28 - 05 25 55 17](https://user-images.githubusercontent.com/120501684/209723944-cbfd40e6-96f8-4e25-aae5-9c447a7700a8.png)
Well, i was trying to sing out my main account and then sign in into my second account. Then i sign to my main account again. That didn't work, the game forced the restart the game and i still have that issue. But i launched the Converter and i see the second Xbox Profile with my Non Xbox profile's name.

**Comment by Steve777475** [comment]
I guess, I should rename Folder taht ends in A3 TO A4 And another one that ends in A4 to A3 i guess....

**Comment by Steve777475** [comment]
Does it give me error because i renamed files?

**Comment by Steve777475** [comment]
![Desktop Screenshot 2022 12 28 - 17 10 51 94](https://user-images.githubusercontent.com/120501684/209788164-97d5f30c-1451-466b-82b6-bbd5e8efef63.png)
I guess i should rename folder A3 TO A4. But I'm not sure if that will work.

**Comment by Steve777475** [comment]
I tried renaming save folder ending in A3 i entered the game it creates the same folder ending in A3

**Comment by Steve777475** [comment]
May be i should play the game and transfer my save?

**Comment by Steve777475** [comment]
Yes, it worked i just moved profile data to Xbox Save FIles. IT FINALLY WORKS THANKS FOR THIS TOOL:)
