### ISSUE TITLE
Forza Horizon 5. The thumbnails seem to load for 1 sec after re-downloading liveries and bug with icons on the map.

### ISSUE THREAD

**Issue by Marat777475** [Fr33dan/GPSaveConverter#32]
So I transfered my progress from Steam to Windows Store using Xbox Save Converter, everything works great but I see that liveries that I re-downloaded load for 1 second if I go to my favorites in my cars (I mean that thumbnails load instantly for 1 second after redownlading liveries). And map icons can glitch when I move cursor to look at the map. Might this be a bug in the game? Or Might I have the bug with my progress?

**Comment by Steve777475** [comment]
It usually happens in my PC Version of the game since I tested my progress on Xbox and I haven't seen that bug from my PC version. That literally bothers me on PC version.

**Comment by Marat777475** [comment]
![20230102_035446.jpg](https://user-images.githubusercontent.com/120501684/210183214-c579fc62-edcf-4e80-a817-93a9bb40a602.jpg) ![20230102_035457.jpg](https://user-images.githubusercontent.com/120501684/210183216-3cb35c67-fec4-432e-89a1-9e01b075e7b0.jpg) ![20230102_202241.jpg](https://user-images.githubusercontent.com/120501684/210230866-a6aca9a8-6e34-4061-a2c0-9096ae649e34.jpg) ![20230102_202259.jpg](https://user-images.githubusercontent.com/120501684/210230877-8f8bb4a4-18d0-4a14-a69b-82b661b17995.jpg)Here. The map and icons glitch and Thumbnails load for 1 second.

**Comment by Marat777475** [comment]
And some challenges from new Series doesn't seem to work.

**Comment by Marat777475** [comment]
Let me know what causes this bug.
