### ISSUE TITLE
Lego star wars conversion

### ISSUE THREAD

**Issue by tymcfie18** [Fr33dan/GPSaveConverter#38]
My lego star wars files are different than what is shown on the other open issue page for star wars. Could someone help me figure out if there is a way to convert these files? 

Game Name:LEGO Star Wars: The Skywalker Saga
Game Package ID:WarnerBros.Interactive.LEGOStarWarsTheSkywalkerSag_ktmk1xygcecda

## Xbox Files:
| Container Name 1 | Container Name 2 | Blob ID |
| ---------------- | ---------------- | ------- |
| profiledata | profiledata | achievements |
| profiledata | profiledata | cutsceneprogress.blob |
| profiledata | profiledata | dlcdata.blob |
| profiledata | profiledata | profiledata.containerinfo |
| profiledata | profiledata | settingsglobalprofile |
| profiledata | profiledata | settingsplayer0profile |
| profiledata | profiledata | settingsplayer1profile |
| profiledata | profiledata | settingsplayer2profile |
| profiledata | profiledata | settingsplayer3profile |
| slot1 | slot1 | achievementsystem.blob |
| slot1 | slot1 | collectables.blob |
| slot1 | slot1 | copilotdata.blob |
| slot1 | slot1 | fogofwarbanks.blob |
| slot1 | slot1 | gameflow.blob |
| slot1 | slot1 | gameprogress.blob |
| slot1 | slot1 | partyfreeplaylist.blob |
| slot1 | slot1 | partysystem.blob |
| slot1 | slot1 | savegamemeta.blob |
| slot1 | slot1 | slot1.containerinfo |
| slot1 | slot1 | texthintnotificationsbanks.blob |
## Non-Xbox Files:
Non-Xbox save location: C:\Users\Mcfie\Desktop\lego_star_wars_the_skywalker_saga\1085046737\
| File Path |
| --------  |
| PROFILEDATA\achievements |
| PROFILEDATA\CUTSCENEPROGRESS.BLOB |
| PROFILEDATA\DLCDATA.BLOB |
| PROFILEDATA\PROFILEDATA.CONTAINERINFO |
| PROFILEDATA\SETTINGSGLOBALPROFILE |
| PROFILEDATA\SETTINGSPLAYER0PROFILE |
| PROFILEDATA\SETTINGSPLAYER1PROFILE |
| PROFILEDATA\SETTINGSPLAYER2PROFILE |
| PROFILEDATA\SETTINGSPLAYER3PROFILE |
| PROFILEDATA\WBPC |
| SLOT1\ACHIEVEMENTSYSTEM.BLOB |
| SLOT1\COLLECTABLES.BLOB |
| SLOT1\COPILOTDATA.BLOB |
| SLOT1\FOGOFWARBANKS.BLOB |
| SLOT1\GAMEFLOW.BLOB |
| SLOT1\GAMEPROGRESS.BLOB |
| SLOT1\PARTYFREEPLAYLIST.BLOB |
| SLOT1\PARTYSYSTEM.BLOB |
| SLOT1\SAVEGAMEMETA.BLOB |
| SLOT1\SLOT1.CONTAINERINFO |
| SLOT1\TEXTHINTNOTIFICATIONSBANKS.BLOB |

**Comment by tymcfie18** [comment]
I am currently looking for other folders that may contain different save files

**Comment by tymcfie18** [comment]
disregard this issue

**Comment by Bcawesomer** [comment]
@tymcfie18 Did you find a fix? if so what was it?
