### ISSUE TITLE
Forza Horizon 4 Error E:80-d

### ISSUE THREAD

**Issue by Fixbound** [Fr33dan/GPSaveConverter#55]
Hi, i'm trying to transfer my progress from the ms-store to steam but im getting the error code E:80-d, i dont know if im doing something wrong, 
![image](https://github.com/Fr33dan/GPSaveConverter/assets/53485556/fdedd4d3-4b53-4c41-ac89-716f9f4c5a9a)

Thats are the files i transfer to my steam folder.

**Comment by iamn** [comment]
same issue

**Comment by hiranokite** [comment]
any fix for this error?

**Comment by kisskisskaty** [comment]
pls. when fix?

**Comment by bakhtyear** [comment]
same issue

**Comment by bakhtyear** [comment]
![E 80-d](https://github.com/Fr33dan/GPSaveConverter/assets/74252241/c34ef161-5921-40ad-9c80-a1bb257e2526)

I've tried moving my MS game file to Steam, but it showed the error 'E:80-d'. Even after putting back my previously backed-up Steam save files, it keeps popping up and I can't play the game.

**Comment by kisskisskaty** [comment]
yep, i have same error code, E:80-d, i think something is wrong with GPSaveConverter, need fix
tried run forza 4 without internet, same error.

**Comment by Fr33dan** [comment]
This has been clearly documented in the wiki for a very long time that FH4 is not compatible.

For many games the different storefront(s) versions use same save files just organized differently with obtuse file names in the Game Pass version. The human readable names are stored in an index file, which is what the converter shows in the GP version file list.

All the converter can do is change the index to add/remove/change files. If those files aren't the same between the versions, then the converter simply isn't (and will not ever be) compatible with that game.

**Comment by SM-AS** [comment]
can it be reverted back i am not able to play
