### ISSUE TITLE
xbox container does not exist forza horizon 4

### ISSUE THREAD

**Issue by ygtraksoy** [Fr33dan/GPSaveConverter#78]
![image_2024-01-21_200527379](https://github.com/Fr33dan/GPSaveConverter/assets/157313940/bd93e307-c6d2-43c6-91f1-e3d719ff408d)

**Comment by Fr33dan** [comment]
[FH4 is not compatible with GPSC](https://github.com/Fr33dan/GPSaveConverter/wiki/Game-Compatibility). There are differences between the Xbox and non-Xbox versions in such a way that it will never be compatible.
