### ISSUE TITLE
does not run under wine

### ISSUE THREAD

**Issue by cipitaua** [Fr33dan/GPSaveConverter#83]
Hello,

I've tried to run GPSC under wine/proton, it starts but then gives an error

![image](https://github.com/Fr33dan/GPSaveConverter/assets/4388859/9f25b975-00f8-4882-8148-47b7c44b1043)

and the program is stuck with status bar saying: "Gettting UWP package manifests..."

Would it be possible to improve wine compatibility?

Thank you

**Comment by Fr33dan** [comment]
I use Proton on my Steam Deck and thus have a cursory understanding of it but haven't fiddle with Wine in years. If you've figured out a way to run games from the Xbox storefront on Linux I would be very interested to know how. I would love to be able to get access to GamePass games on the Deck.

It is my understanding that Proton creates a virtual windows file structure for each application (but this could just be how Steam managed it by default on the Deck). This would mean that in order for GPSC to work, you would somehow need to sync this virtual file structure between the one that runs your Xbox storefront application, the one that contains your non-Xbox installation of the game, and finally the one you wish to run GPSC on.

And then hope that the powershell commands used to get the UWP packages work in this environment.

All in all it would be a huge amount of work for me to even set up an environment to make improvements. Nonetheless the work involved to actually implement the fixes required. I haven't had time lately to give this project the basic support it needs, this kind of major upgrade just isn't in the cards right now.

I'll leave this open though in case someone else wishes to contribute.

**Comment by Fr33dan** [comment]
GPSC Is not intended to support piracy. It's intention is to allow you to move your own save files between games you legitimately have a license to access. 

After recent events I can't emphasis this enough, this is for my own protection.
